### ISSUE TITLE
Node Expansion/Contraction Not Working

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdTools#10]

**Comment by jwaspin** [comment]
@dwalt Is this still a problem? I'm not sure what the issue is since there's no description here but I use chrome and don't have any issues with the nodes so I'm wondering if this was an issue with chrome itself that has since been resolved.

**Comment by dwalt** [comment]
@jwaspin I haven't noticed a problem in recent times, I think it can be closed.
